language: node_js
node_js:
    - iojs
    - "4"
    - "5"
script: npm test
notifications:
    email:
        recipients:
            - zlatkofedor@cherrysro.com
        on_success: change
        on_failure: always

after_script:
 - ./node_modules/.bin/babel-node ./node_modules/.bin/gulp coveralls
